# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default_twitter: &default_twitter
  twitter_api_key: 'M4nAICuq96OKeP0slOmcR9xEG'
  twitter_api_secret: '3k1RFo2ky41B1det1DLACDlsPSShP1Ju7xsUa6LiMAHRZWA2Kr'

development:
  secret_key_base: 359e25d99b797a4f07df6ac1a51f8f8b0b9325bcb367589328920629c1a35498afc1914af9a0aa26e92feb40bbb3bec6e1f99cff1ecbdb58bcbaca7a07ecb4d2
  <<: *default_twitter

test:
  secret_key_base: b655d4a17f13aa4f6c8cc918a8335adcb6651461bc322fa54479400f3b42e4bed8c707a365043ddb140feb904b6ff4c6426f64a711e5348fd031e16048380f1d
  <<: *default_twitter

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
